# Site settings
title: Daniel Breves
description: 'A personal blog attempt'
url: 'http://dbrevesf.github.io/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Daniel Breves'
  email: dbrevesf@gmail.com
  twitter_username: dbreves
  facebook_username: danielbreves
  github_username:  dbrevesf
  linkedin_username:  dbrevesf

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
